"""add customer role for admin authorization

Revision ID: bc91e5814cd7
Revises: 4e6b5978a6ca
Create Date: 2026-09-14 16:39:14.397518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc91e5814cd7'
down_revision: Union[str, Sequence[str], None] = '4e6b5978a6ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('role', sa.String(length=32), server_default='customer', nullable=False))
    op.create_index(op.f('ix_customers_role'), 'customers', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_role'), table_name='customers')
    op.drop_column('customers', 'role')
    # ### end Alembic commands ###
